Add MSI to model
snowio/magento2-data-model pull request #27
Opened 2019-12-02 11:37 UTC by alexanderwanyoike

## Overview

This PR aims to enhance the magento data model with the addition of the SourceItems to manage MSI.

## Tasks
- [x] Add tests for MSI
- [x] Ensure tests pass

2019-12-02 19:58 UTC, nei requested changes

2019-12-02 19:58 UTC, nei commented on src/Inventory/SourceItemData.php
> +            $this->status === $other->status;
shouldn't we compare extension attributes here too?

2019-12-03 11:17 UTC, alexanderwanyoike commented on src/Inventory/SourceItemData.php
> +            $this->status === $other->status;
Yup your right I forgot those as I was using traits

2019-12-03 11:38 UTC, nei approved these changes
👍looks good.

2019-12-03 11:55 UTC, merged